<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { api, json, session } from '@/api'
const router = useRouter(); const mode = ref<'login'|'register'>('login'); const email = ref(''); const password = ref(''); const busy = ref(false); const error = ref('')
async function submit(){busy.value=true;error.value='';try{if(mode.value==='register')await api('/auth/register',{method:'POST',body:json({email:email.value,password:password.value})});const auth=await api<{token?:string}>('/auth/emailpass',{method:'POST',body:json({email:email.value,password:password.value})});if(!auth.token)throw new Error('The wallet API did not return an access token.');session.token=auth.token;const next=router.currentRoute.value.query.next;router.push(typeof next==='string'&&next.startsWith('/')?next:'/wallet')}catch(e){error.value=e instanceof Error?e.message:'Authentication failed'}finally{busy.value=false}}
</script>
<template><section class="auth"><div><span class="pill">Privacy-first proof of age</span><h1>Your credentials. Your choice.</h1><p class="muted">Keep age credentials in a personal wallet and disclose only what a verifier asks for.</p></div><form class="card stack" @submit.prevent="submit"><div><h2>{{ mode==='login'?'Welcome back':'Create your account' }}</h2><p class="muted">Use your email and password to access your wallets.</p></div><label class="field">Email<input v-model="email" required type="email" autocomplete="email" placeholder="you@example.com"></label><label class="field">Password<input v-model="password" required minlength="8" type="password" :autocomplete="mode==='login'?'current-password':'new-password'"></label><div v-if="error" class="notice error">{{ error }}</div><button class="primary" :disabled="busy">{{ busy?'Please wait…':mode==='login'?'Sign in':'Register' }}</button><button type="button" class="quiet" @click="mode=mode==='login'?'register':'login';error=''">{{ mode==='login'?'New here? Create an account':'Already registered? Sign in' }}</button></form></section></template>
<style scoped>.auth{min-height:calc(100vh - 180px);display:grid;grid-template-columns:1.2fr minmax(300px,440px);align-items:center;gap:8vw}.auth>div p{font-size:1.15rem;max-width:570px;line-height:1.65}@media(max-width:780px){.auth{grid-template-columns:1fr}}</style>
