<script setup lang="ts">
import { useRouter } from 'vue-router'
import { session } from './api'
const router = useRouter()
function logout() { session.token = ''; router.push('/auth') }
</script>

<template>
  <header><router-link to="/wallet" class="brand"><img src="/bextrust-mark.svg" alt=""><span><b>Bextrust</b><small>Wallet</small></span></router-link><button v-if="session.token" class="quiet" @click="logout">Sign out</button></header>
  <main><router-view /></main>
</template>

<style>
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#f5f8ff;background:#05070b;font-synthesis:none;--blue:#176bff;--blue-bright:#4185ff}*{box-sizing:border-box}body{margin:0;min-width:320px;background:radial-gradient(circle at 12% -5%,#0b3b8f 0,transparent 34%),#05070b;min-height:100vh}button,input,select,textarea{font:inherit}button{cursor:pointer}header{height:72px;display:flex;align-items:center;justify-content:space-between;padding:0 max(24px,calc((100% - 1120px)/2));border-bottom:1px solid #ffffff18;background:#05070be8;backdrop-filter:blur(12px);position:sticky;top:0;z-index:2}.brand{display:flex;align-items:center;gap:11px;color:#fff;text-decoration:none;letter-spacing:-.02em}.brand img{width:38px;height:38px}.brand span{display:grid;line-height:1}.brand b{font-size:1.05rem}.brand small{margin-top:5px;color:#96a3b7;font-size:.68rem;font-weight:700;letter-spacing:.14em;text-transform:uppercase}main{max-width:1120px;margin:auto;padding:40px 24px 80px}h1,h2,h3,p{margin-top:0}h1{font-size:clamp(2rem,5vw,3.5rem);letter-spacing:-.05em;max-width:760px}.muted{color:#9ba8bb}.card{background:#0d1119;border:1px solid #ffffff18;border-radius:20px;padding:24px;box-shadow:0 20px 60px #0006}.stack{display:grid;gap:16px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:18px}.field{display:grid;gap:7px;color:#b8c2d1;font-size:.9rem}input,select,textarea{width:100%;color:#fff;background:#070a10;border:1px solid #ffffff24;border-radius:11px;padding:12px 13px;outline:none}input:focus,select:focus,textarea:focus{border-color:var(--blue-bright);box-shadow:0 0 0 3px #176bff24}textarea{min-height:120px;resize:vertical}.primary,.secondary,.quiet{border:0;border-radius:11px;padding:11px 16px;color:#fff}.primary{background:var(--blue);font-weight:700}.primary:hover{background:var(--blue-bright)}.secondary{background:#ffffff0d;border:1px solid #ffffff1c}.quiet{background:transparent;color:#c3cad5}.danger{color:#ffaaa2}.notice{border-radius:12px;padding:12px 14px;background:#176bff20;border:1px solid #176bff66}.error{background:#ff625d18;border-color:#ff625d55}.row{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.between{justify-content:space-between}.tabs{display:flex;gap:6px;margin-bottom:24px;overflow:auto}.tabs button{white-space:nowrap}.tabs .active{background:var(--blue)}.item{padding:14px 0;border-top:1px solid #ffffff14;word-break:break-word}.item:first-child{border-top:0}.pill{display:inline-block;padding:4px 8px;border-radius:999px;background:#176bff20;border:1px solid #176bff3d;font-size:.78rem;color:#b9d1ff}pre{white-space:pre-wrap;word-break:break-word;background:#030509;padding:14px;border-radius:10px;color:#bbb;max-height:300px;overflow:auto}@media(max-width:600px){main{padding:28px 16px}header{padding:0 16px}.card{padding:18px}}
.credential-row{display:block;width:100%;background:transparent;border:0;color:inherit;text-align:left}.credential-row:hover{background:#ffffff08}.credential-row.selected{background:#176bff18;border-left:3px solid var(--blue);padding-left:11px}.credential-row .chevron{color:#777;font-size:1.4rem}.credential-detail h2{margin-top:8px}.credential-detail h3{font-size:.9rem;color:#b9bbca;margin:22px 0 8px}.detail-close{font-size:1.5rem;padding:4px 8px}.detail-meta{display:grid;gap:12px;margin-top:20px}.detail-meta div{display:grid;gap:3px;padding-bottom:10px;border-bottom:1px solid #ffffff12;word-break:break-word}.detail-meta small{font-size:.72rem;text-transform:uppercase;letter-spacing:.08em}.detail-empty{min-height:210px;display:grid;place-items:center;align-content:center;text-align:center;color:#8d8fa0}.detail-empty span{font-size:2.3rem;color:var(--blue-bright)}.detail-empty p{margin:8px 0}.wallet-summary{display:flex;gap:10px;flex-wrap:wrap;border-top:1px solid #ffffff12;padding-top:16px}.wallet-summary span{font-size:.82rem;color:#999bab}.wallet-summary b{color:#fff}
</style>
